# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Jani Korpi / Ahkerat Mehilaiset / JKH Service
"""
Epistemic Uncertainty — measures what the system does not know (v3.2).

Score = (missing_baselines + stale_entities + unresolved_questions) / max(total, 1)
Bounded to [0.0, 1.0].

When score > threshold, curiosity goals are generated to actively seek
missing information. Curiosity goals always yield to user goals.
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Protocol

log = logging.getLogger("waggledance.world.epistemic_uncertainty")


# ── Config defaults ──────────────────────────────────────────

DEFAULT_STALE_TTL_SECONDS = 3600  # 1 hour
DEFAULT_UNCERTAINTY_THRESHOLD = 0.4
DEFAULT_CURIOSITY_MAX_PRIORITY = 35
DEFAULT_CURIOSITY_MAX_ACTIVE = {
    "GADGET": 3, "COTTAGE": 5, "HOME": 10, "FACTORY": 20, "APIARY": 10,
}


# ── Protocols ────────────────────────────────────────────────

class BaselineProvider(Protocol):
    """Minimal interface for baseline queries."""
    def get_all_keys(self) -> List[str]: ...


class EntityProvider(Protocol):
    """Minimal interface for entity queries."""
    def list(self, entity_type: Optional[str] = None) -> list: ...


class GoalProvider(Protocol):
    """Minimal interface for goal queries."""
    def get_open_goals(self, goal_type: str = "") -> list: ...


# ── Core ─────────────────────────────────────────────────────

@dataclass
class UncertaintyReport:
    """Result of an uncertainty assessment."""
    score: float = 0.0  # 0.0 = omniscient, 1.0 = total ignorance
    missing_baselines: int = 0
    stale_entities: int = 0
    unresolved_questions: int = 0
    total_tracked: int = 0
    low_confidence_capabilities: int = 0
    stale_entity_ids: List[str] = field(default_factory=list)
    missing_baseline_keys: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "score": round(self.score, 4),
            "missing_baselines": self.missing_baselines,
            "stale_entities": self.stale_entities,
            "unresolved_questions": self.unresolved_questions,
            "low_confidence_capabilities": self.low_confidence_capabilities,
            "total_tracked": self.total_tracked,
            "stale_entity_ids": self.stale_entity_ids[:10],
            "missing_baseline_keys": self.missing_baseline_keys[:10],
        }


@dataclass
class CuriosityGoal:
    """A low-priority observe goal generated by uncertainty."""
    entity_id: str
    description: str
    priority: int  # capped by config
    reason: str  # "stale" | "missing_baseline" | "low_confidence" | "high_error"
    impact_score: float = 0.0  # 0.0–1.0, higher = more impactful


def compute_uncertainty(
    entities: list,
    baseline_keys: set[str],
    open_observe_goals: int = 0,
    stale_ttl_seconds: float = DEFAULT_STALE_TTL_SECONDS,
    now: float | None = None,
    capability_confidence: dict[str, float] | None = None,
    low_confidence_threshold: float = 0.5,
) -> UncertaintyReport:
    """
    Compute epistemic uncertainty score.

    Args:
        entities: list of entity-like objects with entity_id, updated_at
        baseline_keys: set of "entity_id.metric" strings that have baselines
        open_observe_goals: count of unresolved observe-type goals
        stale_ttl_seconds: how old before an entity is considered stale
        now: current time (defaults to time.time())
        capability_confidence: optional {capability_id: confidence} map;
            capabilities below *low_confidence_threshold* contribute to score.
        low_confidence_threshold: confidence below which a capability is
            considered uncertain (default 0.5).
    """
    if now is None:
        now = time.time()

    total = max(len(entities), 1)
    missing = 0
    stale = 0
    stale_ids = []
    missing_keys = []

    for entity in entities:
        eid = getattr(entity, "entity_id", None) or (entity.get("entity_id") if isinstance(entity, dict) else None)
        if not eid:
            continue

        # Stale check
        updated = getattr(entity, "updated_at", None) or (entity.get("updated_at", 0) if isinstance(entity, dict) else 0)
        if (now - updated) > stale_ttl_seconds:
            stale += 1
            stale_ids.append(eid)

        # Missing baseline check — entity should have at least one baseline
        has_baseline = any(k.startswith(f"{eid}.") for k in baseline_keys)
        if not has_baseline:
            missing += 1
            missing_keys.append(eid)

    # Count low-confidence capabilities
    low_conf_count = 0
    if capability_confidence:
        low_conf_count = sum(
            1 for v in capability_confidence.values()
            if v < low_confidence_threshold
        )

    raw = (missing + stale + open_observe_goals + low_conf_count) / total
    score = min(1.0, max(0.0, raw))

    return UncertaintyReport(
        score=score,
        missing_baselines=missing,
        stale_entities=stale,
        unresolved_questions=open_observe_goals,
        low_confidence_capabilities=low_conf_count,
        total_tracked=len(entities),
        stale_entity_ids=stale_ids,
        missing_baseline_keys=missing_keys,
    )


def generate_curiosity_goals(
    report: UncertaintyReport,
    threshold: float = DEFAULT_UNCERTAINTY_THRESHOLD,
    max_priority: int = DEFAULT_CURIOSITY_MAX_PRIORITY,
    max_active: int = 10,
    existing_curiosity_count: int = 0,
    profile: str = "HOME",
) -> List[CuriosityGoal]:
    """
    Generate low-priority observe goals for the most uncertain areas.

    Rules:
    - Only generate when score > threshold
    - Never exceed per-profile max_active
    - Priority capped at max_priority (always yields to user goals)
    """
    if report.score <= threshold:
        return []

    profile_max = DEFAULT_CURIOSITY_MAX_ACTIVE.get(profile.upper(), max_active)
    budget = profile_max - existing_curiosity_count
    if budget <= 0:
        return []

    goals = []

    # Stale entities get curiosity goals first (they had data but it's old)
    for eid in report.stale_entity_ids[:budget]:
        goals.append(CuriosityGoal(
            entity_id=eid,
            description=f"Observe {eid} — data is stale",
            priority=min(max_priority, 30),
            reason="stale",
        ))

    remaining = budget - len(goals)

    # Missing baselines next
    for eid in report.missing_baseline_keys[:remaining]:
        goals.append(CuriosityGoal(
            entity_id=eid,
            description=f"Observe {eid} — no baseline established",
            priority=min(max_priority, 25),
            reason="missing_baseline",
        ))

    return goals


# ── Impact weights ──────────────────────────────────────────────

IMPACT_WEIGHT_ERROR_FREQUENCY = 0.4
IMPACT_WEIGHT_LOW_CONFIDENCE = 0.3
IMPACT_WEIGHT_QUERY_FREQUENCY = 0.2
IMPACT_WEIGHT_STALENESS = 0.1


def _compute_impact(
    topic: str,
    error_frequency: Dict[str, float],
    capability_confidence: Dict[str, float],
    query_counts: Dict[str, int],
    stale_set: set,
    max_queries: int,
) -> float:
    """Compute impact score for a single topic/entity.

    impact = 0.4 * error_freq + 0.3 * (1 - confidence) + 0.2 * query_freq + 0.1 * staleness
    """
    err_freq = error_frequency.get(topic, 0.0)

    # Find the best-matching capability confidence
    conf = 0.5  # default if no match
    for cap_id, c in capability_confidence.items():
        # Match by topic appearing in capability id (e.g. "thermal" in "solve.thermal")
        if topic in cap_id or cap_id.split(".")[-1] == topic:
            conf = c
            break

    query_freq = 0.0
    if max_queries > 0:
        query_freq = min(1.0, query_counts.get(topic, 0) / max_queries)

    staleness = 1.0 if topic in stale_set else 0.0

    return (
        IMPACT_WEIGHT_ERROR_FREQUENCY * err_freq
        + IMPACT_WEIGHT_LOW_CONFIDENCE * (1.0 - conf)
        + IMPACT_WEIGHT_QUERY_FREQUENCY * query_freq
        + IMPACT_WEIGHT_STALENESS * staleness
    )


def generate_impact_curiosity_goals(
    report: UncertaintyReport,
    error_frequency: Optional[Dict[str, float]] = None,
    capability_confidence: Optional[Dict[str, float]] = None,
    query_counts: Optional[Dict[str, int]] = None,
    threshold: float = DEFAULT_UNCERTAINTY_THRESHOLD,
    max_priority: int = DEFAULT_CURIOSITY_MAX_PRIORITY,
    max_active: int = 10,
    existing_curiosity_count: int = 0,
    profile: str = "HOME",
) -> List[CuriosityGoal]:
    """Generate impact-prioritized curiosity goals.

    Unlike :func:`generate_curiosity_goals` which uses a fixed
    stale-then-missing ordering, this function scores every candidate by
    a 4-factor impact formula:

        impact = 0.4 * prediction_error_frequency(topic)
               + 0.3 * (1.0 - capability_confidence(solver))
               + 0.2 * user_query_frequency(topic)
               + 0.1 * staleness(topic)

    Goals are sorted by impact descending and the top *budget* fill the
    per-profile cap.  Topics with zero errors in the last 7 days are
    deprioritized.

    Args:
        report: UncertaintyReport from :func:`compute_uncertainty`.
        error_frequency: {topic: error_rate} from ledger (0.0–1.0).
        capability_confidence: {capability_id: confidence} (0.0–1.0).
        query_counts: {topic: query_count} from ledger.
        threshold: uncertainty score below which no goals are generated.
        max_priority: cap on goal priority (always yield to user goals).
        max_active: default max active curiosity goals.
        existing_curiosity_count: how many curiosity goals already exist.
        profile: runtime profile for per-profile cap.

    Returns:
        List of CuriosityGoal sorted by impact_score descending,
        capped to the per-profile budget.
    """
    if report.score <= threshold:
        return []

    profile_max = DEFAULT_CURIOSITY_MAX_ACTIVE.get(profile.upper(), max_active)
    budget = profile_max - existing_curiosity_count
    if budget <= 0:
        return []

    err_freq = error_frequency or {}
    conf = capability_confidence or {}
    q_counts = query_counts or {}
    max_queries = max(q_counts.values()) if q_counts else 0
    stale_set = set(report.stale_entity_ids)

    # Collect all candidate topics
    candidates: List[tuple] = []  # (topic, reason, description)

    for eid in report.stale_entity_ids:
        candidates.append((eid, "stale", f"Observe {eid} — data is stale"))

    for eid in report.missing_baseline_keys:
        if eid not in stale_set:  # avoid duplicates
            candidates.append((
                eid, "missing_baseline",
                f"Observe {eid} — no baseline established",
            ))

    # Low-confidence capabilities → domain curiosity goals
    for cap_id, c in conf.items():
        if c < 0.5:
            domain = cap_id.split(".")[-1] if "." in cap_id else cap_id
            # Avoid duplicating entity-based candidates
            if not any(cand[0] == domain for cand in candidates):
                candidates.append((
                    domain, "low_confidence",
                    f"Improve {domain} prediction accuracy "
                    f"(confidence {c:.2f})",
                ))

    # High-error intents not already covered
    for intent, rate in err_freq.items():
        if rate > 0.3 and not any(cand[0] == intent for cand in candidates):
            candidates.append((
                intent, "high_error",
                f"Investigate {intent} errors (error rate {rate:.0%})",
            ))

    # Score all candidates
    scored: List[CuriosityGoal] = []
    for topic, reason, description in candidates:
        impact = _compute_impact(
            topic, err_freq, conf, q_counts, stale_set, max_queries,
        )
        scored.append(CuriosityGoal(
            entity_id=topic,
            description=description,
            priority=min(max_priority, 30),
            reason=reason,
            impact_score=round(impact, 4),
        ))

    # Sort by impact descending
    scored.sort(key=lambda g: g.impact_score, reverse=True)

    # Deprioritize zero-error topics: move them to the end
    with_errors = [g for g in scored if err_freq.get(g.entity_id, 0.0) > 0]
    without_errors = [g for g in scored if err_freq.get(g.entity_id, 0.0) == 0]
    scored = with_errors + without_errors

    return scored[:budget]
