# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Jani Korpi / Ahkerat Mehilaiset / JKH Service
"""
Epistemic Uncertainty — measures what the system does not know (v3.2).

Score = (missing_baselines + stale_entities + unresolved_questions) / max(total, 1)
Bounded to [0.0, 1.0].

When score > threshold, curiosity goals are generated to actively seek
missing information. Curiosity goals always yield to user goals.
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Protocol

log = logging.getLogger("waggledance.world.epistemic_uncertainty")


# ── Config defaults ──────────────────────────────────────────

DEFAULT_STALE_TTL_SECONDS = 3600  # 1 hour
DEFAULT_UNCERTAINTY_THRESHOLD = 0.4
DEFAULT_CURIOSITY_MAX_PRIORITY = 35
DEFAULT_CURIOSITY_MAX_ACTIVE = {
    "GADGET": 3, "COTTAGE": 5, "HOME": 10, "FACTORY": 20, "APIARY": 10,
}


# ── Protocols ────────────────────────────────────────────────

class BaselineProvider(Protocol):
    """Minimal interface for baseline queries."""
    def get_all_keys(self) -> List[str]: ...


class EntityProvider(Protocol):
    """Minimal interface for entity queries."""
    def list(self, entity_type: Optional[str] = None) -> list: ...


class GoalProvider(Protocol):
    """Minimal interface for goal queries."""
    def get_open_goals(self, goal_type: str = "") -> list: ...


# ── Core ─────────────────────────────────────────────────────

@dataclass
class UncertaintyReport:
    """Result of an uncertainty assessment."""
    score: float = 0.0  # 0.0 = omniscient, 1.0 = total ignorance
    missing_baselines: int = 0
    stale_entities: int = 0
    unresolved_questions: int = 0
    total_tracked: int = 0
    low_confidence_capabilities: int = 0
    stale_entity_ids: List[str] = field(default_factory=list)
    missing_baseline_keys: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "score": round(self.score, 4),
            "missing_baselines": self.missing_baselines,
            "stale_entities": self.stale_entities,
            "unresolved_questions": self.unresolved_questions,
            "low_confidence_capabilities": self.low_confidence_capabilities,
            "total_tracked": self.total_tracked,
            "stale_entity_ids": self.stale_entity_ids[:10],
            "missing_baseline_keys": self.missing_baseline_keys[:10],
        }


@dataclass
class CuriosityGoal:
    """A low-priority observe goal generated by uncertainty."""
    entity_id: str
    description: str
    priority: int  # capped by config
    reason: str  # "stale" | "missing_baseline"


def compute_uncertainty(
    entities: list,
    baseline_keys: set[str],
    open_observe_goals: int = 0,
    stale_ttl_seconds: float = DEFAULT_STALE_TTL_SECONDS,
    now: float | None = None,
    capability_confidence: dict[str, float] | None = None,
    low_confidence_threshold: float = 0.5,
) -> UncertaintyReport:
    """
    Compute epistemic uncertainty score.

    Args:
        entities: list of entity-like objects with entity_id, updated_at
        baseline_keys: set of "entity_id.metric" strings that have baselines
        open_observe_goals: count of unresolved observe-type goals
        stale_ttl_seconds: how old before an entity is considered stale
        now: current time (defaults to time.time())
        capability_confidence: optional {capability_id: confidence} map;
            capabilities below *low_confidence_threshold* contribute to score.
        low_confidence_threshold: confidence below which a capability is
            considered uncertain (default 0.5).
    """
    if now is None:
        now = time.time()

    total = max(len(entities), 1)
    missing = 0
    stale = 0
    stale_ids = []
    missing_keys = []

    for entity in entities:
        eid = getattr(entity, "entity_id", None) or (entity.get("entity_id") if isinstance(entity, dict) else None)
        if not eid:
            continue

        # Stale check
        updated = getattr(entity, "updated_at", None) or (entity.get("updated_at", 0) if isinstance(entity, dict) else 0)
        if (now - updated) > stale_ttl_seconds:
            stale += 1
            stale_ids.append(eid)

        # Missing baseline check — entity should have at least one baseline
        has_baseline = any(k.startswith(f"{eid}.") for k in baseline_keys)
        if not has_baseline:
            missing += 1
            missing_keys.append(eid)

    # Count low-confidence capabilities
    low_conf_count = 0
    if capability_confidence:
        low_conf_count = sum(
            1 for v in capability_confidence.values()
            if v < low_confidence_threshold
        )

    raw = (missing + stale + open_observe_goals + low_conf_count) / total
    score = min(1.0, max(0.0, raw))

    return UncertaintyReport(
        score=score,
        missing_baselines=missing,
        stale_entities=stale,
        unresolved_questions=open_observe_goals,
        low_confidence_capabilities=low_conf_count,
        total_tracked=len(entities),
        stale_entity_ids=stale_ids,
        missing_baseline_keys=missing_keys,
    )


def generate_curiosity_goals(
    report: UncertaintyReport,
    threshold: float = DEFAULT_UNCERTAINTY_THRESHOLD,
    max_priority: int = DEFAULT_CURIOSITY_MAX_PRIORITY,
    max_active: int = 10,
    existing_curiosity_count: int = 0,
    profile: str = "HOME",
) -> List[CuriosityGoal]:
    """
    Generate low-priority observe goals for the most uncertain areas.

    Rules:
    - Only generate when score > threshold
    - Never exceed per-profile max_active
    - Priority capped at max_priority (always yields to user goals)
    """
    if report.score <= threshold:
        return []

    profile_max = DEFAULT_CURIOSITY_MAX_ACTIVE.get(profile.upper(), max_active)
    budget = profile_max - existing_curiosity_count
    if budget <= 0:
        return []

    goals = []

    # Stale entities get curiosity goals first (they had data but it's old)
    for eid in report.stale_entity_ids[:budget]:
        goals.append(CuriosityGoal(
            entity_id=eid,
            description=f"Observe {eid} — data is stale",
            priority=min(max_priority, 30),
            reason="stale",
        ))

    remaining = budget - len(goals)

    # Missing baselines next
    for eid in report.missing_baseline_keys[:remaining]:
        goals.append(CuriosityGoal(
            entity_id=eid,
            description=f"Observe {eid} — no baseline established",
            priority=min(max_priority, 25),
            reason="missing_baseline",
        ))

    return goals
