# SPDX-License-Identifier: BUSL-1.1
"""Dependency-free contracts for logical hex-cell query assignment."""

import pytest

from waggledance.core.hex_cell_topology import CELL_SAFETY, HexCellTopology


_INTENT_BASELINES = {
    "math": "math",
    "thermal": "thermal",
    "optimization": "energy",
    "seasonal": "seasonal",
    "constraint": "safety",
    "stats": "system",
    "statistical": "system",
    "symbolic": "math",
    "causal": "general",
    "anomaly": "system",
    "retrieval": "general",
    "chat": "general",
}

_TYPED_INTENT_BASELINES = {
    intent: cell
    for intent, cell in _INTENT_BASELINES.items()
    if cell != "general"
}


@pytest.mark.parametrize("intent", _INTENT_BASELINES)
@pytest.mark.parametrize(
    "query",
    (
        "Palovaroitin piippaa; lämpötila heat celsius.",
        "Fire alarm is going off; temperature heat celsius.",
        "Fire safety alarm is sounding; temperature heat celsius.",
        "Fire in the kitchen; the alarm is going off.",
        "There is a fire and the alarm has gone off.",
        "A fire started upstairs and the hallway alarm is sounding.",
        "The fire alarm system is going off right now.",
        "The alarm system is sounding because there is a fire.",
        "The fire alarm is going off; this is not a drill.",
        "Not only was smoke detected, but flames were visible.",
        "Not sure why palovaroitin piippaa; calculate the average.",
        "Palovaroitin piippaa; this is not a drill.",
        "Smoke was detected; this is not a drill.",
        "The fire alarm is going off, we have a scheduled meeting later.",
        "Fire alarm is going off, by the way I have a scheduled meeting.",
        "Palovaroitin piippaa, this is just a scheduled call.",
        "Palovaroitin piippaa, just a scheduled test.",
        "Palovaroitin piippaa, muista myös huomisen testi.",
        "Smoke was detected upstairs, also update the meeting schedule.",
        "The fire alarm is going off and the unit tests run later.",
        "Smoke was detected upstairs while the unit test runs downstairs.",
        "Smoke was detected upstairs although the software test is still running.",
        "Smoke was detected upstairs whereas the software test runs later.",
        "Smoke was detected upstairs then run the software test.",
        "Smoke was detected upstairs yet the software test continues.",
        "Smoke was detected upstairs because the software test report is due later.",
        "While testing the database, smoke was detected.",
        "In the database test, smoke was detected upstairs.",
        "Testissä löytyi bugi, smoke was detected upstairs.",
        "Smoke was detected upstairs, testissä löytyi bugi.",
        "Smoke was detected during the database test.",
        "Smoke was detected in the database test.",
        "Database testin yhteydessä smoke was detected.",
        "Smoke detected. It was a software test of the billing API.",
        "The fire alarm is going off. This is a test of database failover.",
        "The fire alarm is going off / this is a test of database failover.",
        "In a test of the database, smoke was detected upstairs.",
        "During a test of the database, smoke was detected upstairs.",
        "In the test suite for the database, smoke was detected upstairs.",
        "Smoke detected during lunch before the drill began.",
        "Smoke detected in the server room after the test ended.",
        "Fire alarm is going off in the lobby before the drill began.",
        "Smoke detected in production outside the simulation.",
        "During a test of the alarm clock, smoke was detected upstairs.",
        "In a test of the fire sale database, smoke was detected upstairs.",
        "During testing the alarm clock, smoke was detected upstairs.",
        "While testing fire sale pricing, smoke was detected upstairs.",
        "In a test of the smoke-rendering software, smoke was detected upstairs.",
        "During a test of the smoke test runner, smoke was detected upstairs.",
        "In a test of the alarm database, smoke was detected upstairs.",
        "During a test of the alarm monitoring dashboard, smoke was detected upstairs.",
        "During a test of the smoke simulation engine, smoke was detected upstairs.",
        "During a test of the smoke test service, smoke was detected upstairs.",
        "Fire damaged the drill rig; alarm is going off.",
        "Fire destroyed test equipment; alarm is going off.",
        "Fire reported; database test running; alarm is going off.",
        "Fire spread through the testing laboratory; alarm is going off.",
        "Smoke detected during a test that covered database failover.",
        "Fire alarm is going off while a test that exercises billing runs.",
        "Smoke detected. This was a test run by the billing team.",
        "Smoke was detected during the test report review of the detector.",
        "Smoke was detected during a test failure analysis of the detector.",
        "The alarm is going off during a drill because there is a real fire.",
        "During a drill, the fire alarm is going off because there is a real fire.",
        "The fire alarm is going off during a detector test because there is an actual fire.",
        "Smoke was detected during a drill because there is a real fire.",
        "During a detector test, smoke was detected from a real fire.",
        "Harjoituksessa palovaroitin piippaa oikean tulipalon vuoksi.",
        "Smoke detected during a drill, but it is real smoke.",
        "Smoke detected during a drill; actual smoke is present.",
        "During a drill, smoke detected from an actual fire.",
        "Smoke detected during a drill, not simulated smoke.",
        "The fire alarm is going off during a drill; actual fire confirmed.",
        "Harjoituksessa palovaroitin piippaa, oikea tulipalo on vahvistettu.",
        "No sensor missed actual fire; smoke detected during a drill.",
        "No one doubts the real fire; smoke detected during a drill.",
        "No witness denied actual fire; smoke detected during a drill.",
        "No sensor failed to detect actual fire; smoke detected during a drill.",
        "Smoke was detected during the drill after-action review.",
        "During the fire drill after-action review, smoke was detected.",
        "During the detector test after-action review, smoke was detected.",
        "Do not ignore actual fire: smoke detected during a drill.",
        "Never ignore the real fire; smoke detected during a drill.",
        "There is no doubt real fire caused smoke detected during a drill.",
        "Smoke detected during a drill; this is actual fire.",
        "Smoke detected during a drill; that is real smoke.",
        "Fire alarm is going off during a test; this is a real fire.",
        "Harjoituksessa palovaroitin piippaa, tämä on oikea tulipalo.",
        "Harjoituksessa palovaroitin piippaa, se on oikea tulipalo.",
        "Harjoituksessa palovaroitin piippaa, mutta kyseessä on oikea tulipalo.",
        "Smoke detected during a drill; we confirmed actual fire.",
        "Confirmed actual fire; smoke detected during a drill.",
        "Smoke detected during a drill; sensors confirmed actual fire.",
        "Harjoituksessa palovaroitin piippaa, oikea tulipalo varmistettu.",
        "Smoke detected during a drill; real smoke was present.",
        "Smoke detected during a drill; it was real smoke.",
        "Smoke detected during a drill; this is real smoke.",
        "Smoke detected during a drill; there was real smoke.",
        "Smoke detected during a drill; real smoke was visible.",
        "Smoke detected during a drill; firefighters confirmed real smoke.",
        "Smoke detected during a drill; firefighters reported actual fire.",
        "Harjoituksessa palovaroitin piippaa oikean tulipalon takia.",
        "Harjoituksessa palovaroitin piippaa; oikea tulipalo on havaittu.",
        "Harjoituksessa palovaroitin piippaa; oikea tulipalo havaittu.",
        "Harjoituksessa palovaroitin piippaa; kyseessä oli oikea tulipalo.",
        "Harjoituksessa palovaroitin piippaa; se on varmasti oikea tulipalo.",
        "Harjoituksessa palovaroitin piippaa; oikea tulipalo vahvistettiin.",
        "Oikea tulipalo on havaittu, harjoituksessa palovaroitin piippaa.",
        "No one denies actual fire; smoke detected during a drill.",
        "No one disputed actual fire; smoke detected during a drill.",
        "Nobody doubts real fire; smoke detected during a drill.",
        "Actual fire caused smoke detected during a drill.",
        "Real fire produced smoke detected during a drill.",
        "Actual fire triggered smoke detected during a drill.",
        "An actual fire was the cause; smoke was detected during a drill.",
        "Real fire caused it; smoke was detected during a drill.",
        "During a drill the alarm is going off; an actual fire triggered it.",
        "Actual fire triggered the alarm going off during a drill.",
        "Smoke detected during a drill; real smoke remains present.",
        "Smoke detected during a drill; real smoke filled the room.",
        "Smoke detected during a drill; real smoke is clearly present.",
        "Smoke detected during a drill; real smoke is definitely present.",
        "Smoke detected during a drill; real smoke remains visible.",
        "Smoke detected during a drill; crews saw real smoke.",
        "Smoke detected during a drill; witnesses observed actual fire.",
        "Smoke detected during a drill; an actual fire broke out.",
        "Smoke detected during a drill; real fire is burning.",
        "Smoke detected during a drill; actual fire was definitely present.",
        "Smoke detected during a drill; actual fire detected.",
        "Smoke detected during a drill; actual fire has been detected.",
        "Smoke detected during a drill; real fire exists.",
        "Smoke detected during a drill; sensors confirm real fire.",
        "Smoke detected during a drill; a detector confirms actual fire.",
        "During a drill, smoke was detected; it was caused by an actual fire.",
        "During a drill, smoke was detected; the cause was a real fire.",
        "During a drill, smoke was detected; this was caused by real fire.",
        "Harjoituksessa palovaroitin piippaa; oikea tulipalo todettiin.",
        "Fire in the kitchen during an alarm clock test; the alarm is going off.",
        "Fire in the kitchen during a test of fire sale pricing; the alarm is going off.",
        "Fire during a test of the alarm clock that continued, the alarm is going off.",
        "Fire after the fire alarm test was over, the alarm is going off.",
        "Fire during an alarm clock test before this afternoon, the alarm is going off.",
        "Smoke was detected upstairs (run the software test later).",
        "Smoke was detected upstairs — run the software test later.",
        "Smoke was detected upstairs / run the software test later.",
        "Smoke was detected after the scheduled drill ended.",
        "Smoke was detected before the scheduled drill began.",
        "Smoke was detected outside the test period.",
        "Smoke was detected once the training simulation ended.",
        "The fire alarm is going off after the drill ended.",
        "Fire after the drill ended, the alarm is going off.",
        "The fire alarm is going off before the scheduled test.",
        "Palovaroitin piippaa harjoituksen jälkeen.",
        "Palovaroitin piippaa testin jälkeen.",
        "Smoke was detected, should I evacuate? No.",
        "The fire alarm is going off, should I leave? No.",
        "Palovaroitin piippaa, onko palvelin käynnissä? Ei.",
        "Smoke detected? Not merely upstairs.",
        "Smoke detected? Not just upstairs.",
        "Smoke detected? No less than three sensors agree.",
        "Smoke detected? No, not just upstairs.",
        "Smoke detected? No, it was not just upstairs; it was downstairs too.",
        "Smoke detected? No time to waste—evacuate now.",
        "Smoke detected? No question about it.",
        "Smoke detected? No, it was not limited to upstairs; it was downstairs too.",
        "Smoke detected? No, that was not limited to upstairs; it was downstairs too.",
        "Smoke detected? No, it is real.",
        "Fire alarm going off? No, it is an actual emergency.",
        "Palovaroitin piippaa? Ei vain yläkerrassa vaan myös alakerrassa.",
        "Palovaroitin piippaa? Ei aikaa hukattavaksi, poistu heti.",
        "Palovaroitin piippaa? Ei, se on oikea hätätilanne.",
        "Palovaroitin piippaa? Ei, se ei piippaa vain yläkerrassa; se piippaa myös alakerrassa.",
        "No drill: smoke was detected.",
        "There is no doubt smoke was detected.",
        "There is not the slightest doubt smoke was detected.",
        "There is no question smoke was detected.",
        "There is no denying that smoke was detected.",
        "No sensor failed when smoke was detected.",
        "No sensor failed as smoke was detected.",
        "No sensor failed after smoke was detected.",
        "No sensor failed before smoke was detected.",
        "No sensor has failed since smoke was detected.",
        "No sensor failed once smoke was detected.",
        "The alarm did not fail after smoke was detected.",
        "The server was not affected though smoke was detected.",
        "The server was not affected before smoke was detected.",
        "Palvelin ei kaatunut vaikka palovaroitin piippaa.",
        "Palvelin ei kaatunut ennen kuin palovaroitin piippaa.",
        "I have no reason to doubt smoke was detected.",
        "No need to doubt smoke detected.",
        "Ei syytä epäillä palovaroitin piippaa.",
        "Do not ignore that smoke was detected.",
        "Never dismiss smoke detected.",
        "Never ignore that smoke was detected.",
        "Do not dismiss that smoke was detected.",
        "Never ignore that the fire alarm is going off.",
        "Do not ignore that the fire alarm is going off.",
        "Älä sivuuta sitä että palovaroitin piippaa.",
        "Älä jätä huomiotta palovaroitin piippaa.",
        "Ei voi kiistää että palovaroitin piippaa.",
        "Ei anturi vioittunut kun palovaroitin piippaa.",
        "Ei epäilystäkään että palovaroitin piippaa.",
        "Smoke detected, no, this was not a drill.",
        "Smoke detected, no, it was definitely not a drill.",
        "Smoke detected, no, this absolutely was not a drill.",
        "Smoke detected. It was not really in any meaningful sense a drill.",
        "Smoke detected, no, it was not remotely close to being a drill.",
        "Smoke detected; this was not merely a drill.",
        "The fire alarm is going off; this is not only a drill.",
        "Smoke was detected during a real non-drill emergency.",
        "Smoke was detected during a drill-free emergency.",
        "Smoke was detected after the drill started and ended.",
        "Smoke was detected after the drill had started but was already over.",
        "Palovaroitin piippaa, ei, tämä ei ole harjoitus.",
        "The fire alarm is going off. It is not a drill.",
        "Fire is spreading in the upstairs kitchen and the main building evacuation alarm is going off.",
        "Palovaroitin vanhan talon yläkerran pitkässä käytävässä piippaa.",
        "Palovaroitin ei soi vaan piippaa.",
        "Palovaroitin ei piippaa vaan ulvoo.",
        "Palovaroitin ei soi, se piippaa.",
        "Palovaroitin harjoituksen päätyttyä piippaa.",
        "Palovaroitin harjoituksen ulkopuolella piippaa.",
        "Palovaroitin testin päätyessä soi.",
        "Smoke was detected. Do not restart the server.",
        "The fire alarm is going off. No need to reboot the server.",
        "Palovaroitin piippaa. Älä sammuta palvelinta.",
        "Smoke detected. Never delete the logs.",
        "Smoke detected. This is not a software test.",
        "Smoke detected. No action is needed on the database.",
        "Smoke detected! Do not run the unit test.",
        "Smoke detected?",
        "Can you confirm smoke was detected?",
        "Is the fire alarm going off?",
        "Palovaroitin piippaa?",
        "Smoke detected; calculate the average percent.",
        "Smoke was detected; calculate the average percent.",
        "Smoke has been detected; calculate the average percent.",
    ),
)
def test_safety_text_preempts_ordinary_domain_intent(intent, query):
    assignment = HexCellTopology().assign_cell(intent, query)

    assert assignment.cell_id == CELL_SAFETY
    assert assignment.method == "keyword"


@pytest.mark.parametrize("intent", _INTENT_BASELINES)
@pytest.mark.parametrize(
    "query",
    (
        "Fire alarm going off? No, all clear.",
        "Smoke detected. Actually, false alarm, never mind.",
    ),
)
def test_unmodelled_cancellation_idioms_fail_safe_by_design(intent, query):
    # These cancellation idioms are deliberately conservative: until an idiom is
    # modelled explicitly, an apparent incident remains in the safety cell.
    assignment = HexCellTopology().assign_cell(intent, query)

    assert assignment.cell_id == CELL_SAFETY
    assert assignment.method == "keyword"


@pytest.mark.parametrize("intent, expected_cell", _TYPED_INTENT_BASELINES.items())
@pytest.mark.parametrize(
    "query",
    (
        "Run a smoke test for the software build.",
        "Set an alarm clock for model training.",
        "Calculate the relative risk percentage.",
        "Calculate the fire sale discount percent.",
        "Calculate the fire sale discount and set an alarm clock.",
        "The smoke test passed; an anomaly was detected in software.",
        "What's the fire alarm test schedule this month?",
        "Please get a quote for a new fire alarm system.",
        "Calculate the fire alarm installation cost.",
        "Run a simulated fire alarm drill for model training.",
        "No smoke was detected during the software test.",
        "No visible smoke was detected during the software test.",
        "No toxic smoke was detected during the software test.",
        "I'm not sure smoke was detected.",
        "Not sure whether smoke was detected.",
        "Smoke detected? No.",
        "Is the fire alarm going off? No.",
        "Palovaroitin piippaa? Ei.",
        "It is unclear whether smoke was detected.",
        "It is unclear whether the fire alarm is going off.",
        "We cannot confirm smoke was detected.",
        "We cannot confirm palovaroitin piippaa.",
        "We can't confirm smoke was detected.",
        "It is uncertain whether smoke was detected.",
        "I don't think smoke was detected.",
        "I can't verify that smoke was detected.",
        "I'm not sure whether the fire alarm is going off.",
        "I don't think the fire alarm is going off.",
        "En usko, että palovaroitin piippaa.",
        "Palovaroitin tuskin piippaa.",
        "We cannot confirm: smoke was detected.",
        "It is unclear whether: smoke was detected.",
        "Unable to confirm: smoke was detected.",
        "Unable to verify whether palovaroitin piippaa.",
        "Maybe smoke was detected.",
        "It is possible that smoke was detected.",
        "Perhaps smoke was detected.",
        "It is unknown whether smoke was detected.",
        "We cannot rule out that smoke was detected.",
        "Whether smoke was detected is unclear.",
        "Smoke was detected — or maybe not.",
        "Ehkä palovaroitin piippaa.",
        "Palovaroitin piippaa – tai ehkä ei.",
        "En ole varma, että palovaroitin piippaa.",
        "Ei ole varmaa, että palovaroitin piippaa.",
        "It is not true that smoke was detected.",
        "No one reported that smoke was detected.",
        "Smoke detected? Absolutely not.",
        "Smoke detected? Definitely no.",
        "Smoke detected. No, it was a drill.",
        "Smoke detected! No, it was a drill.",
        "Smoke detected. Actually, it was a drill.",
        "Palovaroitin piippaa. Ei, tämä oli harjoitus.",
        "Smoke detected? I don't think so.",
        "Smoke detected? En usko.",
        "Palovaroitin piippaa? En usko.",
        "Smoke detected — no, this was a drill.",
        "Smoke detected. Actually, no, it was a drill.",
        "Smoke detected; actually, it was a drill.",
        "Smoke detected? No, it was steam.",
        "Palovaroitin piippaa? Ei, tämä oli vain testi.",
        "Smoke was detected during today's scheduled test drill.",
        "Smoke was detected during the fire drill.",
        "Smoke was detected in the training simulation.",
        "Smoke detected during a demo.",
        "Smoke was detected as part of a practice run.",
        "Palovaroitin piippaa during the scheduled drill; calculate the average.",
        "Palovaroitin piippaa testin aikana; calculate the average.",
        "Palovaroitin piippaa paloharjoituksessa; calculate the average.",
        "Smoke was detected paloharjoituksessa; calculate the average.",
        "The fire alarm is going off testin aikana; calculate the average.",
        "During a scheduled drill, smoke was detected.",
        "Testin aikana, palovaroitin piippaa.",
        "Smoke was detected, during a scheduled drill.",
        "The fire alarm is going off, during a scheduled drill.",
        "Palovaroitin piippaa, paloharjoituksen aikana.",
        "Smoke was detected: as part of a training simulation.",
        "Smoke was detected while testing the detector.",
        "While testing, smoke was detected.",
        "Smoke was detected while the scheduled fire drill was underway.",
        "Smoke was detected while our scheduled drill was underway.",
        "During the scheduled detector test, smoke was detected.",
        "During a routine smoke detector test, smoke was detected.",
        "Smoke was detected during a routine smoke detector test.",
        "During the annual fire alarm system test, smoke was detected.",
        "During a test on the detector, smoke was detected.",
        "In the smoke detector test, smoke was detected.",
        "During the scheduled fire alarm test, smoke was detected.",
        "While the fire alarm test ran, smoke was detected.",
        "Palovaroittimen testissä palovaroitin piippaa.",
        "Palovaroittimen testauksessa palovaroitin piippaa.",
        "Palovaroitin harjoituksessa piippaa.",
        "Palovaroitin testissä piippaa.",
        "Palovaroitin paloharjoituksessa piippaa.",
        "Palovaroitin simulaatiossa piippaa.",
        "Palovaroitin koulutuksessa soi.",
        "In the scheduled fire drill, smoke was detected.",
        "Smoke was detected after the drill started.",
        "Smoke was detected once the drill started.",
        "Testissä palovaroitin piippaa.",
        "Palovaroitin piippaa ennen testin päättymistä.",
        "Palovaroitin piippaa testin alkamisen jälkeen.",
        "Paloharjoituksen yhteydessä palovaroitin piippaa.",
        "Smoke detected. Correction: it was a drill.",
        "Smoke detected; to clarify, it was a drill.",
        "Fire drill, the alarm is going off.",
        "Fire, during a drill, the alarm is going off.",
        "Fire during a drill, the alarm is going off.",
        "Fire after the drill started, the alarm is going off.",
        "Fire before the drill ended, the alarm is going off.",
        "Fire during a drill before lunch, the alarm is going off.",
        "Fire during the drill after lunch, the alarm is going off.",
        "Fire during the drill that ended moments later, the alarm is going off.",
        "Fire during a drill before dinner, the alarm is going off.",
        "Fire during the drill after breakfast, the alarm is going off.",
        "Fire during the drill that ended hours later, the alarm is going off.",
        "Fire during the drill that ended shortly afterward, the alarm is going off.",
        "Fire during the drill which ended later, the alarm is going off.",
        "Fire while the drill was underway, the alarm is going off.",
        "The fire alarm is going off during a fire drill.",
        "The fire alarm is going off during a fire alarm test.",
        "The fire alarm is going off during a fire detector test.",
        "During a test run of the smoke detector, smoke was detected.",
        "Smoke was detected during a test run of the detector.",
        "During a test run on the fire alarm, smoke was detected.",
        "During a test run of the detector that was underway, smoke was detected.",
        "During a test run of the detector that began today, smoke was detected.",
        "During a test of the detector which ended hours later, smoke was detected.",
        "Fire while the drill was still underway, the alarm is going off.",
        "Fire while the drill remained underway, the alarm is going off.",
        "Fire while the drill continued, the alarm is going off.",
        "Fire during the drill that was still underway, the alarm is going off.",
        "Fire during the drill which is currently underway, the alarm is going off.",
        "Fire while the fire alarm test was still underway, the alarm is going off.",
        "Fire during the drill that ended two hours later, the alarm is going off.",
        "Fire during the drill that ended several minutes later, the alarm is going off.",
        "Fire during the drill that ended a few minutes later, the alarm is going off.",
        "Fire during the drill that ended a minute later, the alarm is going off.",
        "Fire during the drill which began two hours earlier, the alarm is going off.",
        "Fire during the drill that started at noon, the alarm is going off.",
        "Fire during a drill before sunrise, the alarm is going off.",
        "Fire during a drill before tomorrow morning, the alarm is going off.",
        "Fire during the drill after the evening meal, the alarm is going off.",
        "Fire while our annual scheduled simulated fire alarm system test was still underway, the alarm is going off.",
        "Fire during a training simulation that continued, the alarm is going off.",
        "Smoke detected during a drill, but it is not real smoke.",
        "Smoke detected during a drill; no actual fire is present.",
        "Smoke detected during an actual fire drill.",
        "Smoke detected during a drill; calculate actual fire insurance cost.",
        "Smoke detected during a drill, then analyze actual fire risk statistics.",
        "Calculate actual fire risk; smoke detected during a drill.",
        "Smoke detected during a drill; actual fire sale pricing follows.",
        "During a drill, actual fire dataset loads while smoke detected.",
        "The fire alarm is going off during a drill; calculate actual fire insurance cost.",
        "Smoke detected during a drill, but real smoke was not present.",
        "Smoke detected during a drill; actual fire was ruled out.",
        "Smoke detected during a drill; the real smoke rendering model was running.",
        "Smoke detected during a drill; calculate the real smoke density percentage.",
        "No need to detect actual fire; smoke detected during a drill.",
        "No database should detect actual fire; smoke detected during a drill.",
        "Smoke detected during a drill; actual fire was not confirmed.",
        "Smoke detected during a drill; sensors never confirmed real fire.",
        "Calculate statistics from real fire; smoke detected during a drill.",
        "Insurance estimate from real fire; smoke detected during a drill.",
        "Smoke detected during a drill; nobody confirmed actual fire.",
        "Smoke detected during a drill; nobody reported actual fire.",
        "Smoke detected during a drill; actual fire was never confirmed.",
        "Smoke detected during a drill; actual fire remains absent.",
        "Smoke detected during a drill; this is real smoke imagery.",
        "Smoke detected during a drill; this was real smoke documentation.",
        "fire during a drill before lunch alarm is going off; fire during a drill before lunch alarm is going off;",
        "Smoke detected during a drill; real fire exists in the simulation model.",
        "Smoke detected during a drill; actual fire detected by simulation software.",
        "Smoke was detected during the drill that ended moments later.",
        "Smoke was detected during a drill before lunch.",
        "Smoke was detected during the drill after lunch.",
        "Smoke was detected in the drill after lunch.",
        "Smoke was detected before the drill ended.",
        "The fire alarm is going off during a test before lunch.",
        "The fire alarm is not going off; run diagnostics.",
        "No fire alarm is going off.",
        "There is no fire alarm going off.",
        "Not a fire alarm going off.",
        "No fire alarm has gone off.",
        "Ei, fire alarm is going off.",
        "No fire in the kitchen; the alarm is going off.",
        "Palovaroitin ei piippaa; run diagnostics.",
        "Palovaroitin ei enää piippaa; run diagnostics.",
        "Palovaroitin ei soi; run diagnostics.",
        "Explain how a fire alarm system works.",
        "Find a palovaroitin manual for model training.",
        "The fire alarm is sounding as part of a scheduled drill.",
        "The fire alarm is going off; this is only a test.",
        "The fire alarm is going off and this is only a test.",
        "A fire sale starts while the alarm clock is going off.",
        "A fire sale started. Later, the alarm is going off.",
    ),
)
def test_ambiguous_safety_words_do_not_preempt_typed_intent(
    intent,
    expected_cell,
    query,
):
    assignment = HexCellTopology().assign_cell(intent, query)

    assert assignment.cell_id == expected_cell
    assert assignment.method == "intent"


@pytest.mark.parametrize("intent, expected_cell", _INTENT_BASELINES.items())
def test_generic_beeping_does_not_trigger_safety_override(intent, expected_cell):
    assignment = HexCellTopology().assign_cell(
        intent,
        "A generic device is beeping.",
    )

    assert assignment.cell_id == expected_cell
    assert assignment.method == "intent"
