sources:
- id: src:NEK1
  org: SML
  title: Mehiläishoitoa käytännössä + satokasvitiedot
  year: 2011
  url: null
  identifier: ISBN 978-952-92-9184-4
  supports: Satokasvit, nektarivirtaus, linkoaminen.
