#!/usr/bin/env python3
"""Auto-commit + push campaign artifacts at regular intervals.

Commits evidence files (campaign_state.json, hot_results.jsonl,
incident_log.jsonl, new segment_metrics_*.json / segment_report_*.md,
daily_summary_*.md). Regenerates Phase 6/7 reports first so latest
aggregate is always in the commit.

Pushes to origin/main. If push fails (network / auth expired), the
commit is still made locally — next successful push will catch up.

Run with:
    python tools/campaign_auto_commit.py \\
        --campaign-dir docs/runs/ui_gauntlet_400h_20260413_092800 \\
        --interval-minutes 60

Safe to run alongside campaign_watchdog.py — different .pid file.
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent


def log(msg: str) -> None:
    print(f"[{datetime.now(timezone.utc).isoformat(timespec='seconds')}] {msg}",
          flush=True)


def run(cmd: list[str], timeout: int = 120, cwd: Path = ROOT) -> tuple[int, str, str]:
    try:
        p = subprocess.run(cmd, cwd=str(cwd), timeout=timeout,
                            capture_output=True, text=True)
        return p.returncode, p.stdout, p.stderr
    except subprocess.TimeoutExpired:
        return 124, "", "timeout"
    except Exception as e:
        return 1, "", str(e)


def regenerate_reports(campaign_dir: Path) -> None:
    """Regenerate Phase 6/7/9 reports from current evidence."""
    py = str(ROOT / ".venv" / "Scripts" / "python.exe")
    rc, out, err = run([py, str(ROOT / "tools" / "campaign_reports.py"),
                         "all",
                         "--campaign-dir", str(campaign_dir),
                         "--main-ref", "main~30"],
                        timeout=120)
    if rc == 0:
        log("reports regenerated")
    else:
        log(f"report regeneration failed rc={rc} err={err[:200]}")


def stage_and_commit(campaign_dir: Path) -> bool:
    """Stage campaign artifacts and commit if there are changes."""
    patterns = [
        str(campaign_dir / "campaign_state.json"),
        str(campaign_dir / "hot_results.jsonl"),
        str(campaign_dir / "incident_log.jsonl"),
        str(campaign_dir / "segment_metrics_*.json"),
        str(campaign_dir / "segment_report_*.md"),
        str(campaign_dir / "daily_summary_*.md"),
        str(campaign_dir / "weekly_rollup_*.md"),
        str(campaign_dir / "final_*.md"),
        str(campaign_dir / "final_findings.json"),
        str(campaign_dir / "release_followup_decision_400h.md"),
    ]
    for pat in patterns:
        run(["git", "add"] + [pat], timeout=30)

    # Check if there's anything staged
    rc, out, _ = run(["git", "diff", "--cached", "--name-only"], timeout=15)
    if not out.strip():
        return False

    # Compose commit message with current state
    try:
        import json
        state = json.load(open(campaign_dir / "campaign_state.json", encoding="utf-8"))
        h = state["cumulative_hours"]
        segs = state.get("segments_completed", 0)
        msg = (f"campaign(400h): auto-checkpoint "
               f"HOT={h['hot']:.1f}h WARM={h['warm']:.1f}h COLD={h['cold']:.1f}h "
               f"TOTAL={h['total']:.1f}h ({h['total']/400*100:.1f}%) segs={segs}")
    except Exception:
        msg = f"campaign(400h): auto-checkpoint {datetime.now(timezone.utc).isoformat(timespec='seconds')}"

    full = msg + "\n\nAuto-generated by tools/campaign_auto_commit.py — regenerated Phase 6/7/9 reports\nbefore commit. Running alongside campaign_watchdog.py.\n"

    rc, out, err = run(["git", "commit", "-m", full], timeout=30)
    if rc == 0:
        log(f"committed: {msg}")
        return True
    log(f"commit failed rc={rc} err={err[:200]}")
    return False


def try_push(timeout: int = 120) -> bool:
    env = os.environ.copy()
    env["GIT_TERMINAL_PROMPT"] = "0"
    try:
        p = subprocess.run(["git", "push", "origin", "main"],
                            cwd=str(ROOT), timeout=timeout, env=env,
                            capture_output=True, text=True)
        if p.returncode == 0:
            log("pushed to origin/main")
            return True
        log(f"push failed rc={p.returncode}: {p.stderr[:300]}")
        return False
    except subprocess.TimeoutExpired:
        log(f"push timed out after {timeout}s (credential prompt?)")
        return False
    except Exception as e:
        log(f"push exception: {e}")
        return False


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--campaign-dir", required=True, type=Path)
    ap.add_argument("--interval-minutes", type=float, default=60.0,
                    help="Minutes between auto-commits")
    ap.add_argument("--once", action="store_true",
                    help="Run once and exit (for cron-style use)")
    args = ap.parse_args()

    cdir: Path = args.campaign_dir
    pid_file = cdir / ".auto_commit.pid"

    # Single-instance guard
    if pid_file.exists():
        try:
            import psutil
            old = int(pid_file.read_text().strip())
            if psutil.pid_exists(old):
                log(f"another auto-commit already running (pid={old}), exiting")
                return 1
        except Exception:
            pass
    pid_file.write_text(str(os.getpid()))

    log(f"starting auto-commit, interval={args.interval_minutes}min, dir={cdir}")

    try:
        while True:
            regenerate_reports(cdir)
            committed = stage_and_commit(cdir)
            if committed:
                try_push()
            else:
                log("no changes to commit")

            if args.once:
                break

            time.sleep(args.interval_minutes * 60)
    except KeyboardInterrupt:
        log("stopped by user")
    finally:
        try:
            pid_file.unlink(missing_ok=True)
        except Exception:
            pass

    return 0


if __name__ == "__main__":
    sys.exit(main())
